# configure isort to be compatible with black
# source: https://black.readthedocs.io/en/stable/compatible_configs.html#configuration
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]



[tool.flake8]
exclude = ["__pycache__", "pyproject.toml",]
max-line-length = 88
# per-file-ignores = __init__.py:F401
ignore = [
    "E203", # Whitespace before ':'. Ignored for black compatibility
    "W503", # Line break occurred before a binary operator. Ignored for black compatibility
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D105",# Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "SC200", # Spelling error in name (e.g. variable, function, class)
    ]
# ban-relative-imports = True
# docstring-convention = google
# inline-quotes = "


[tool.mypy]
plugins = ["mypy_django_plugin.main"]
disallow_untyped_defs = true


[tool.django-stubs]
django_settings_module = "primo.settings"


# mypy may eventually need this or something similar.
# [tool.mypy-.migrations]
# ignore_errors = true
