# configure isort to be compatible with black
# source: https://black.readthedocs.io/en/stable/compatible_configs.html#configuration
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
exclude = '''
/(
    migrations
  | manage.py
  | settings.py
)/
'''

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
disallow_untyped_defs = true

[tool.django-stubs]
django_settings_module = "primo.settings"


# mypy may eventually need this or something similar.
# [tool.mypy-.migrations]
# ignore_errors = true
