# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0019_bodypart_tree_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='islandregion',
            options={'managed': True, 'ordering': ['island_name'], 'verbose_name': 'Island region'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'managed': True, 'ordering': ['taxon_name'], 'verbose_name_plural': 'taxa'},
        ),
        migrations.RenameField(
            model_name='bodypart',
            old_name='name',
            new_name='bodypart_name',
        ),
        migrations.RenameField(
            model_name='captive',
            old_name='captive',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='fossil',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='islandregion',
            old_name='name',
            new_name='island_name',
        ),
        migrations.RenameField(
            model_name='observer',
            old_name='name',
            new_name='observer_name',
        ),
        migrations.RenameField(
            model_name='original',
            old_name='original',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rankname',
            new_name='rank_name',
        ),
        migrations.RenameField(
            model_name='sex',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='name',
            new_name='taxon_name',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='name',
            new_name='variable_name',
        ),
    ]
