# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0020_auto_20170328_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='islandregion',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Island region'},
        ),
        migrations.AlterModelOptions(
            name='stateprovince',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'State/province', 'verbose_name_plural': 'States/provinces'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'taxa'},
        ),
        migrations.RenameField(
            model_name='bodypart',
            old_name='bodypart_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='continent',
            old_name='continent_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='institute',
            old_name='institute_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='islandregion',
            old_name='island_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='locality',
            old_name='locality_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='observer',
            old_name='observer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rank_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stateprovince',
            old_name='state_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='taxon_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='variable_name',
            new_name='name',
        ),
    ]
