# Generated by Django 2.0.5 on 2018-06-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0022_auto_20170329_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authgrouppermissions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthGroup'),
        ),
        migrations.AlterField(
            model_name='authgrouppermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthPermission'),
        ),
        migrations.AlterField(
            model_name='authpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.DjangoContentType'),
        ),
        migrations.AlterField(
            model_name='authusergroups',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthGroup'),
        ),
        migrations.AlterField(
            model_name='authusergroups',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthUser'),
        ),
        migrations.AlterField(
            model_name='authuseruserpermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthPermission'),
        ),
        migrations.AlterField(
            model_name='authuseruserpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthUser'),
        ),
        migrations.AlterField(
            model_name='bodypart',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.Bodypart'),
        ),
        migrations.AlterField(
            model_name='bodypartvariable',
            name='bodypart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Bodypart'),
        ),
        migrations.AlterField(
            model_name='bodypartvariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Variable'),
        ),
        migrations.AlterField(
            model_name='captive',
            name='name',
            field=models.CharField(blank=True, choices=[('captive', 'captive'), ('wild-caught', 'wild-caught'), ('probably captive', 'probably captive')], max_length=16, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='data3d',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Session'),
        ),
        migrations.AlterField(
            model_name='data3d',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Variable'),
        ),
        migrations.AlterField(
            model_name='djangoadminlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.DjangoContentType'),
        ),
        migrations.AlterField(
            model_name='djangoadminlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthUser'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Locality'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Continent'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='island_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.IslandRegion'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state_province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.StateProvince'),
        ),
        migrations.AlterField(
            model_name='original',
            name='name',
            field=models.CharField(blank=True, choices=[('original', 'original'), ('cast', 'cast')], max_length=16, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='protocolvariable',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Protocol'),
        ),
        migrations.AlterField(
            model_name='protocolvariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Variable'),
        ),
        migrations.AlterField(
            model_name='querywizardtable',
            name='query_wizard_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='primo.QueryWizardQuery'),
        ),
        migrations.AlterField(
            model_name='scalar',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Session'),
        ),
        migrations.AlterField(
            model_name='scalar',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Variable'),
        ),
        migrations.AlterField(
            model_name='session',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='primo.AuthGroup'),
        ),
        migrations.AlterField(
            model_name='session',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Observer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Original'),
        ),
        migrations.AlterField(
            model_name='session',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Protocol'),
        ),
        migrations.AlterField(
            model_name='session',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Specimen'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='ageclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AgeClass'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='captive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Captive'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='fossil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Fossil'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Institute'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Locality'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Sex'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Taxon'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Type'),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Country'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='fossil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Fossil'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.Taxon'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Rank'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='datatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Datatype'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='laterality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Laterality'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='pairing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.Variable'),
        ),
        migrations.AlterModelTable(
            name='authgrouppermissions',
            table=None,
        ),
        migrations.AlterModelTable(
            name='authusergroups',
            table=None,
        ),
        migrations.AlterModelTable(
            name='authuseruserpermissions',
            table=None,
        ),
    ]
