# Generated by Django 2.0.5 on 2018-06-07 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0026_auto_20180607_0144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='SpecimenType',
        ),
        migrations.RenameField(
            model_name='specimen',
            old_name='type',
            new_name='specimentype',
        ),
        migrations.AlterField(
            model_name='bodypart',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.Bodypart', verbose_name='Parent Bodypart'),
        ),
        migrations.AlterField(
            model_name='captive',
            name='name',
            field=models.CharField(blank=True, choices=[('captive', 'captive'), ('wild-caught', 'wild-caught'), ('probably captive', 'probably captive')], max_length=16, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='abbr',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='islandregion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region Name'),
        ),
        migrations.AlterField(
            model_name='paired',
            name='name',
            field=models.CharField(blank=True, choices=[('Paired', 'Paired'), ('Unpaired', 'Unpaired')], max_length=64, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Original', verbose_name='Original or Cast'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='captive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Captive', verbose_name='Captive or Wild'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='fossil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.Fossil', verbose_name='Fossil or Extant'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.Taxon', verbose_name='Parent Taxon'),
        ),
    ]
