# Generated by Django 2.0.5 on 2018-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0027_auto_20180607_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimentype',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Specimen Type'),
        ),
    ]
