# Generated by Django 2.1.1 on 2018-10-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0030_auto_20180624_2252'),
    ]

    operations = [
    ]
