# Generated by Django 2.1.1 on 2019-07-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0031_auto_20181031_1530'),
    ]

    operations = [
    ]
