# Generated by Django 2.1.1 on 2019-07-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0033_auto_20190717_1236'),
    ]

    operations = [
    ]
