# Generated by Django 2.1.1 on 2019-07-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0035_auto_20190717_1308'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='age_class',
        #     old_name='age_class',
        #     new_name='name',
        # ),
        # migrations.RenameField(
        #     model_name='institute',
        #     old_name='institute_dept',
        #     new_name='institute_department',
        # ),
        # migrations.RenameField(
        #     model_name='laterality',
        #     old_name='laterality',
        #     new_name='name',
        # ),
        # migrations.RenameField(
        #     model_name='querywizardquery',
        #     old_name='query_type',
        #     new_name='data_table',
        # ),
        # migrations.RenameField(
        #     model_name='variable',
        #     old_name='pairing',
        #     new_name='paired_with',
        # ),
        # migrations.RenameField(
        #     model_name='specimen',
        #     old_name='specimentype',
        #     new_name='specimen_type',
        # ),
        # migrations.AlterField(
        #     model_name='authpermission',
        #     name='content_type',
        #     field=models.IntegerField(),
        # ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default=10000, max_length=191, unique=True, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='locality',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.PROTECT, to='primo.Locality'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='islandregion',
            name='name',
            field=models.CharField(blank=True, default=10000, max_length=255, verbose_name='Region Name'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='island_region',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.PROTECT, to='primo.IslandRegion'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state_province',
            field=models.ForeignKey(default=10000, null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.StateProvince'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='institute',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.PROTECT, to='primo.Institute'),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='abbr',
            field=models.CharField(max_length=8, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='country',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.PROTECT, to='primo.Country'),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='name',
            field=models.CharField(max_length=255, verbose_name='State'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='authgrouppermissions',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='authuseruserpermissions',
        #     unique_together=set(),
        # ),
        # migrations.AlterModelTable(
        #     name='ageclass',
        #     table='age_class',
        # ),
        # migrations.AlterModelTable(
        #     name='authpermission',
        #     table=None,
        # ),
        # migrations.AlterModelTable(
        #     name='specimentype',
        #     table='specimen_type',
        # ),
        # migrations.RemoveField(
        #     model_name='authgrouppermissions',
        #     name='permission',
        # ),
        # migrations.RemoveField(
        #     model_name='authuseruserpermissions',
        #     name='permission',
        # ),
    ]
