# Generated by Django 2.1.1 on 2019-07-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0038_authgrouppermissions'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='ageclass',
        #     old_name='age_class',
        #     new_name='name',
        # ),
        migrations.AlterField(
            model_name='locality',
            name='state_province',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.PROTECT, to='primo.StateProvince'),
        ),
        # migrations.AlterField(
        #     model_name='specimen',
        #     name='captive',
        #     field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.PROTECT, to='primo.Captive'),
        # ),
        migrations.AlterField(
            model_name='specimen',
            name='fossil',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.PROTECT, to='primo.Fossil'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='mass',
            field=models.IntegerField(default=0),
        ),
    ]
