# Generated by Django 2.1.1 on 2019-08-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0039_auto_20190726_1546'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='institute',
        #     name='institute_dept',
        # ),
        # migrations.RemoveField(
        #     model_name='laterality',
        #     name='laterality',
        # ),
        # migrations.RemoveField(
        #     model_name='querywizardquery',
        #     name='query_type',
        # ),
        # migrations.AddField(
        #     model_name='institute',
        #     name='institute_department',
        #     field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department'),
        # ),
        # migrations.AddField(
        #     model_name='laterality',
        #     name='name',
        #     field=models.CharField(blank=True, choices=[('none', 'none'), ('transverse', 'transverse'), ('median', 'median'), ('right', 'right'), ('left', 'left')], max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='querywizardquery',
        #     name='data_table',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
    ]
