# Generated by Django 2.1.1 on 2019-08-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0041_auto_20190801_1601'),
    ]

    operations = [
    #     migrations.AlterUniqueTogether(
    #         name='authuseruserpermissions',
    #         unique_together=set(),
    #     ),
    #     migrations.RemoveField(
    #         model_name='authuseruserpermissions',
    #         name='permission',
    #     ),
    #     migrations.RemoveField(
    #         model_name='authuseruserpermissions',
    #         name='user',
    #     ),
        # migrations.RenameField(
        #     model_name='ageclass',
        #     old_name='age_class',
        #     new_name='name',
        # ),
        # migrations.RenameField(
        #     model_name='institute',
        #     old_name='institute_dept',
        #     new_name='institute_department',
        # ),
        # migrations.RenameField(
        #     model_name='laterality',
        #     old_name='laterality',
        #     new_name='name',
        # ),
        # migrations.RenameField(
        #     model_name='querywizardquery',
        #     old_name='query_type',
        #     new_name='data_table',
        # ),
        # migrations.RenameField(
        #     model_name='variable',
        #     old_name='pairing',
        #     new_name='paired_with',
        # ),
        # migrations.RemoveField(
        #     model_name='specimen',
        #     name='specimentype',
        # ),
        # migrations.AddField(
        #     model_name='specimen',
        #     name='specimen_type',
        #     field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='primo.SpecimenType'),
        # ),
        # migrations.AlterField(
        #     model_name='specimen',
        #     name='ageclass',
        #     field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='primo.Ageclass'),
        # ),
        # migrations.AlterField(
        #     model_name='specimen',
        #     name='fossil',
        #     field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.PROTECT, to='primo.Fossil'),
        # ),
        # migrations.DeleteModel(
        #     name='AuthUserUserPermissions',
        # ),
    ]
