# Generated by Django 2.1.1 on 2019-08-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0042_auto_20190801_1623'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='specimen',
        #     name='ageclass',
        #     field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='primo.Ageclass'),
        # ),
        # migrations.AlterField(
        #     model_name='specimen',
        #     name='fossil',
        #     field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='primo.Fossil'),
        # ),
    ]
