# Generated by Django 2.1.1 on 2019-08-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0053_auto_20190806_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scalar',
            new_name='DataScalar',
        ),
        migrations.AlterModelOptions(
            name='datascalar',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'scalar data', 'verbose_name_plural': 'scalar data'},
        ),
        migrations.AlterField(
            model_name='specimen',
            name='ageclass',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='primo.Ageclass'),
        ),
        # migrations.AlterModelTable(
        #     name='data_3d',
        #     table='data_3d',
        # ),
        # migrations.AlterModelTable(
        #     name='data_scalar',
        #     table='data_scalar',
        # ),
        # migrations.AlterModelTable(
        #     name='specimentype',
        #     table='specimentype',
        # ),
    ]
