# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0021_auto_20170329_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captive',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fossil',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='original',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sex',
            old_name='value',
            new_name='name',
        ),
    ]
