# Generated by Django 2.0.5 on 2018-06-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0025_auto_20180607_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paired',
            old_name='paired',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ageclass',
            name='abbr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='captive',
            name='name',
            field=models.CharField(blank=True, choices=[('captive', 'captive'), ('wild-caught', 'wild-caught'), ('probably captive', 'probably captive')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='abbr',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='abbr',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_dept',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institure'),
        ),
        migrations.AlterField(
            model_name='laterality',
            name='abbr',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='original',
            name='abbr',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='original',
            name='name',
            field=models.CharField(blank=True, choices=[('original', 'original'), ('cast', 'cast')], max_length=16, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='paired',
            name='abbr',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='abbr',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='abbr',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='abbr',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
