# Generated by Django 2.1.1 on 2019-07-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0032_auto_20190717_1222'),
    ]

    operations = [
    ]
