# Generated by Django 2.1.1 on 2019-07-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0036_auto_20190719_1315'),
    ]

    operations = [

        # migrations.RenameField(
        #     model_name='institute',
        #     old_name='institute_dept',
        #     new_name='institute_department',
        # ),
        # migrations.RenameField(
        #     model_name='laterality',
        #     old_name='laterality',
        #     new_name='name',
        # ),
        # migrations.RenameField(
        #     model_name='querywizardquery',
        #     old_name='query_type',
        #     new_name='data_table',
        # ),
        # migrations.RenameField(
        #     model_name='specimen',
        #     old_name='ageclass',
        #     new_name='age_class',
        # ),
        # migrations.RenameField(
        #     model_name='variable',
        #     old_name='pairing',
        #     new_name='paired_with',
        # ),
        # migrations.RemoveField(
        #     model_name='specimen',
        #     name='specimentype',
        # ),
        # migrations.AddField(
        #     model_name='specimen',
        #     name='specimen_type',
        #     field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='primo.SpecimenType'),
        # ),
        # migrations.AlterModelTable(
        #     name='ageclass',
        #     table='age_class',
        # ),
        # migrations.AlterModelTable(
        #     name='specimentype',
        #     table='specimen_type',
        # ),
        # migrations.DeleteModel(
        #     name='AuthGroupPermissions',
        # ),
        # migrations.DeleteModel(
        #     name='AuthUserUserPermissions',
        # ),
    ]
