# Generated by Django 2.1.1 on 2019-07-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0037_auto_20190719_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthGroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primo.AuthPermission')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
