# Generated by Django 5.2.9 on 2026-05-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Captive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "captive_or_wild",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("captive", "Captive"),
                            ("wild-caught", "Wild-caught"),
                            ("probably captive", "Probably Captive"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="Captive or wild-caught",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Abbreviation"
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "captive",
                "db_table": "captive",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "continent_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Africa", "Africa"),
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("Australia", "Australia"),
                            ("North America", "North America"),
                            ("South America", "South America"),
                            ("Unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                        unique=True,
                        verbose_name="Continent name",
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "continent",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        default=10000, max_length=191, verbose_name="Country name"
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "country",
                "ordering": ["country_name"],
            },
        ),
        migrations.CreateModel(
            name="Datatype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("scalar", "Scalar"),
                            ("data3d", "3D data"),
                            ("external", "External"),
                        ],
                        default="scalar",
                        max_length=32,
                        verbose_name="Data type",
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "data type",
                "db_table": "data_type",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DebugModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("force_change", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "device",
            },
        ),
        migrations.CreateModel(
            name="Fossil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fossil_or_extant",
                    models.CharField(
                        choices=[
                            ("fossil", "Fossil"),
                            ("extant", "Extant"),
                            ("unknown", "Unknown"),
                        ],
                        default="fossil",
                        max_length=16,
                        unique=True,
                        verbose_name="Fossil or Extant",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Abbreviation"
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Fossil or Extant",
                "verbose_name_plural": "Fossil or Extant",
                "db_table": "fossil",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Laterality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laterality",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("transverse", "Transverse"),
                            ("median", "Median"),
                            ("right", "Right"),
                            ("left", "Left"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=255,
                        verbose_name="Laterality",
                    ),
                ),
                ("abbr", models.CharField(max_length=1, verbose_name="Abbreviation")),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "laterality",
                "db_table": "laterality",
            },
        ),
        migrations.CreateModel(
            name="Observer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("researcher_name", models.CharField(max_length=191, unique=True)),
                (
                    "initials",
                    models.CharField(blank=True, max_length=4, null=True, unique=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "observer",
                "ordering": ["researcher_name"],
            },
        ),
        migrations.CreateModel(
            name="Original",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_or_cast",
                    models.CharField(
                        choices=[("original", "Original"), ("cast", "Cast")],
                        default="original",
                        max_length=16,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        unique=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "original",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="Protocol label"),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "protocol",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QueryWizardQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_table", models.CharField(blank=True, max_length=20, null=True)),
                ("query", models.TextField(blank=True, null=True)),
                ("query_suffix", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "query_wizard_query",
            },
        ),
        migrations.CreateModel(
            name="Sex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("male?", "Male?"),
                            ("female?", "Female?"),
                            ("possibly male", "Possibly male"),
                            ("possibly female", "Possibly female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="Sex",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Abbreviation"
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "sexes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomicRank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(max_length=255, verbose_name="Taxonomic rank"),
                ),
            ],
            options={
                "db_table": "taxonomic_rank",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomicType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taxonomic_type",
                    models.CharField(
                        choices=[
                            ("holotype", "Holotype"),
                            ("lectotype", "Lectotype"),
                            ("syntype", "Syntype"),
                            ("neotype", "Neotype"),
                            ("future neotype", "Future neotype"),
                            ("future lectotype", "Future lectotype"),
                        ],
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Abbreviation"
                    ),
                ),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "taxonomic type",
                "db_table": "taxonomic_type",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Bodypart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=191, unique=True, verbose_name="Bodypart name"
                    ),
                ),
                ("expand_in_tree", models.BooleanField(default=False)),
                ("tree_root", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.bodypart",
                        verbose_name="Parent Bodypart",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locality_name",
                    models.CharField(max_length=191, verbose_name="Locality"),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "continent",
                    models.ForeignKey(
                        default=7,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="web.continent",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        default=10000,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="web.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "localities",
                "db_table": "locality",
                "ordering": ["locality_name"],
            },
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Abbreviation"
                    ),
                ),
                (
                    "institute_name",
                    models.CharField(max_length=255, verbose_name="Institute"),
                ),
                (
                    "institute_department",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Department"
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "locality",
                    models.ForeignKey(
                        default=10000,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="web.locality",
                    ),
                ),
            ],
            options={
                "db_table": "institute",
                "ordering": ["institute_name"],
            },
        ),
        migrations.CreateModel(
            name="QueryWizardTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "filter_table_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("preselected", models.BooleanField(default=False)),
                (
                    "query_wizard_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tables",
                        to="web.querywizardquery",
                    ),
                ),
            ],
            options={
                "db_table": "query_wizard_table",
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hypocode", models.CharField(blank=True, max_length=20)),
                (
                    "catalog_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("mass", models.IntegerField(default=0)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "captive",
                    models.ForeignKey(
                        default=9,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.captive",
                    ),
                ),
                (
                    "fossil",
                    models.ForeignKey(
                        default=9,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.fossil",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        default=10000,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.institute",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        default=10000,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="web.locality",
                    ),
                ),
                (
                    "sex",
                    models.ForeignKey(
                        default=9,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.sex",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iteration", models.IntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="auth.group"
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.observer"
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.original",
                        verbose_name="Original or Cast",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.protocol"
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.specimen"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Taxon name"
                    ),
                ),
                ("expand_in_tree", models.BooleanField(default=False)),
                ("tree_root", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "fossil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.fossil"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.taxon",
                        verbose_name="Parent Taxon",
                    ),
                ),
                (
                    "taxonomic_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.taxonomicrank",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "taxa",
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="specimen",
            name="taxon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="web.taxon"
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="taxonomic_type",
            field=models.ForeignKey(
                default=7,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.taxonomictype",
            ),
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=32)),
                ("variable_name", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "datatype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.datatype"
                    ),
                ),
                (
                    "laterality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.laterality"
                    ),
                ),
                (
                    "paired_with",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.variable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataScalar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.session"
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.variable"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scalar data",
                "verbose_name_plural": "Scalar data",
                "db_table": "data_scalar",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Data3D",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datindex", models.IntegerField(blank=True, null=True)),
                (
                    "x",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=9999.0,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=9999.0,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "z",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=9999.0,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.session"
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.variable"
                    ),
                ),
            ],
            options={
                "verbose_name": "3D data",
                "verbose_name_plural": "3D data",
                "db_table": "data_3d",
            },
        ),
        migrations.CreateModel(
            name="BodypartVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bodypart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.bodypart"
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.variable"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bodypart-variable link",
                "db_table": "bodypart_variable",
                "ordering": ["id"],
            },
        ),
    ]
