# Generated by Django 5.2.9 on 2026-05-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DebugModel",
        ),
    ]
