# Generated by Django 5.2.9 on 2026-05-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("web", "0002_delete_debugmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fossil",
            old_name="fossil_or_extant",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="sex",
            old_name="sex",
            new_name="label",
        ),
        migrations.AlterField(
            model_name="session",
            name="group",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.PROTECT, to="auth.group"
            ),
        ),
        migrations.AlterModelTable(
            name="bodypart",
            table="bodypart",
        ),
        migrations.AlterModelTable(
            name="session",
            table="session",
        ),
        migrations.AlterModelTable(
            name="sex",
            table="sex",
        ),
        migrations.AlterModelTable(
            name="specimen",
            table="specimen",
        ),
        migrations.AlterModelTable(
            name="taxon",
            table="taxon",
        ),
        migrations.AlterModelTable(
            name="variable",
            table="variable",
        ),
    ]
