# Generated by Django 5.2.9 on 2026-05-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_rename_fossil_or_extant_fossil_label_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fossil",
            old_name="label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="sex",
            old_name="label",
            new_name="name",
        ),
    ]
