# Generated by Django 5.2.9 on 2026-05-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_rename_label_fossil_name_rename_label_sex_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fossil",
            old_name="name",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="sex",
            old_name="name",
            new_name="label",
        ),
    ]
