# Generated by Django 5.2.9 on 2026-08-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_add_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="iteration",
        ),
    ]
