# Generated by Django 5.2.9 on 2026-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_remove_iteration_from_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
