"""
Lookup table of variable names based on tooth type.

The initial table is based on the teeth.xls file of Eric Delson, where the type of
specimen (column A) determines the names of the variables provided. For example,
if the specimen is of type '01UIC', then the variable in column 6 is 'UI1W'. But
if it's of type '02UPR', then the variable in column M is 'UP3W'.

This section is hand-edited and delicate—be careful changing it!

Originally, the first 7 columns held specimen-specific metadata from the teeth.xls,
with columns 8 and greater holding the variable names, but since that data was
specimen-specific it was unneccesary, so I removed it. Likewise with the last
three columns, which hel random stuff like comments. If the variable name is
blank no data should exist in that column for that specimen type.
"""

variable_names = {
    "01UIC": [
        "",
        "",
        "",
        "",
        "",
        "UI1W",
        "UI1LA",
        "UI1L",
        "UI1H",
        "UI1RH",
        "UI1TH",
        "UI2W",
        "UI2LA",
        "UI2L",
        "UI2H",
        "UI2RH",
        "UI2TH",
        "UCW",
        "UCL",
        "UCH",
        "UCRH",
        "UCTH",
    ],
    "02UPR": [
        "",
        "UP3WG",
        "UP4WG",
        "UP3WS",
        "UP4WS",
        "UP3W",
        "UP3L",
        "UP3IC",
        "UP3H",
        "UP3FH",
        "UP3AL",
        "UP3PL",
        "UP4W",
        "UP4L",
        "UP4IC",
        "UP4H",
        "UP4FH",
        "UP4AL",
        "UP4PL",
        "",
        "",
        "",
    ],
    "03UM1": [
        "",
        "UM1WG",
        "UM1WS",
        "",
        "",
        "UM1AW",
        "UM1AWN",
        "UM1PW",
        "UM1PWN",
        "UM1L",
        "UM1ICA",
        "UM1ICP",
        "UM1ICB",
        "UM1ICL",
        "UM1NH",
        "UM1H",
        "UM1AL",
        "UM1PL",
        "",
        "",
        "",
        "",
    ],
    "04UM2": [
        "",
        "UM2WG",
        "UM2WS",
        "",
        "",
        "UM2AW",
        "UM2AWN",
        "UM2PW",
        "UM2PWN",
        "UM2L",
        "UM2ICA",
        "UM2ICP",
        "UM2ICB",
        "UM2ICL",
        "UM2NH",
        "UM2H",
        "UM2AL",
        "UM2PL",
        "",
        "",
        "",
        "",
    ],
    "05UM3": [
        "",
        "UM3WG",
        "UM3WS",
        "",
        "",
        "UM3AW",
        "UM3AWN",
        "UM3PW",
        "UM3PWN",
        "UM3L",
        "UM3ICA",
        "UM3ICP",
        "UM3ICB",
        "UM3ICL",
        "UM3NH",
        "UM3H",
        "UM3AL",
        "UM3PL",
        "",
        "",
        "",
        "",
    ],
    "06LIC": [
        "",
        "",
        "",
        "LI1W",
        "LI1LA",
        "LI1L",
        "LI1H",
        "LI1RH",
        "LI1TH",
        "LI2W",
        "LI2LA",
        "LI2L",
        "LI2H",
        "LI2RH",
        "LI2TH",
        "LCW",
        "LCL",
        "LCH",
        "LCRH",
        "LCTH",
        "",
        "",
    ],
    "07LPR": [
        "",
        "LP4WG",
        "LP4WS",
        "LP3W",
        "LP3LA",
        "LP3L",
        "LP3FL",
        "LP3H",
        "LP3PL",
        "LP3HX",
        "LP4W",
        "LP4L",
        "LP4IC",
        "LP4NH",
        "LP4MH",
        "LP4FH",
        "LP4ALN",
        "LP4PLN",
        "LP4ALM",
        "LP4PLM",
        "",
        "",
    ],
    "08LM1": [
        "",
        "LM1WG",
        "LM1WS",
        "LM1AW",
        "LM1AWN",
        "LM1PW",
        "LM1PWN",
        "LM1L",
        "LM1ICA",
        "LM1ICP",
        "LM1ICB",
        "LM1ICL",
        "LM1NH",
        "LM1H",
        "LM1AL",
        "LM1PL",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "09LM2": [
        "",
        "LM2WG",
        "LM2WS",
        "LM2AW",
        "LM2AWN",
        "LM2PW",
        "LM2PWN",
        "LM2L",
        "LM2ICA",
        "LM2ICP",
        "LM2ICB",
        "LM2ICL",
        "LM2NH",
        "LM2H",
        "LM2AL",
        "LM2PL",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "10LM3": [
        "",
        "LM3WG",
        "LM3WS",
        "LM3AW",
        "LM3AWN",
        "LM3PW",
        "LM3PWN",
        "LM3L",
        "LM3ICA",
        "LM3ICP",
        "LM3ICB",
        "LM3ICL",
        "LM3NH",
        "LM3H",
        "LM3AL",
        "LM3PL",
        "LM3HW",
        "LM3HW2",
        "LM3IHB",
        "LM3IHL",
        "LM3AL2",
        "LM3HYL",
    ],
    "11UCD": [
        "",
        "",
        "",
        "",
        "",
        "UDI1W",
        "UDI1LA",
        "UDI1L",
        "UDI1H",
        "UDI1RH",
        "UDI1TH",
        "UDI2W",
        "UDI2LA",
        "UDI2L",
        "UDI2H",
        "UDI2RH",
        "UDI2TH",
        "UDCW",
        "UDCL",
        "UDCH",
        "UDCRH",
        "UDCTH",
    ],
    # Common variable name typo, so, add a line to deal with it:
    "11UDC": [
        "",
        "",
        "",
        "",
        "",
        "UDI1W",
        "UDI1LA",
        "UDI1L",
        "UDI1H",
        "UDI1RH",
        "UDI1TH",
        "UDI2W",
        "UDI2LA",
        "UDI2L",
        "UDI2H",
        "UDI2RH",
        "UDI2TH",
        "UDCW",
        "UDCL",
        "UDCH",
        "UDCRH",
        "UDCTH",
    ],
    "12UD3": [
        "",
        "UD3WG",
        "UD3WS",
        "",
        "",
        "UD3AW",
        "UD3AWN",
        "UD3PW",
        "UD3PWN",
        "UD3L",
        "UD3ICA",
        "UD3ICP",
        "UD3ICB",
        "UD3ICL",
        "UD3NH",
        "UD3H",
        "UD3AL",
        "UD3PL",
        "",
        "",
        "",
        "",
    ],
    "13UD4": [
        "",
        "UD4WG",
        "UD4WS",
        "",
        "",
        "UD4AW",
        "UD4AWN",
        "UD4PW",
        "UD4PWN",
        "UD4L",
        "UD4ICA",
        "UD4ICP",
        "UD4ICB",
        "UD4ICL",
        "UD4NH",
        "UD4H",
        "UD4AL",
        "UD4PL",
        "",
        "",
        "",
        "",
    ],
    # Common variable name typo, so, add a line to deal with it:
    "13LDC": [
        "",
        "",
        "",
        "LDI1W",
        "LDI1LA",
        "LDI1L",
        "LDI1H",
        "LDI1RH",
        "LDI1TH",
        "LDI2W",
        "LDI2LA",
        "LDI2L",
        "LDI2H",
        "LDI2RH",
        "LDI2TH",
        "LDCW",
        "LDCL",
        "LDCH",
        "LDCRH",
        "LDCTH",
        "",
        "",
    ],
    "14LDC": [
        "",
        "",
        "",
        "LDI1W",
        "LDI1LA",
        "LDI1L",
        "LDI1H",
        "LDI1RH",
        "LDI1TH",
        "LDI2W",
        "LDI2LA",
        "LDI2L",
        "LDI2H",
        "LDI2RH",
        "LDI2TH",
        "LDCW",
        "LDCL",
        "LDCH",
        "LDCRH",
        "LDCTH",
        "",
        "",
    ],
    # Common variable name typo, so, add a line to deal with it:
    "14LCD": [
        "",
        "",
        "",
        "LDI1W",
        "LDI1LA",
        "LDI1L",
        "LDI1H",
        "LDI1RH",
        "LDI1TH",
        "LDI2W",
        "LDI2LA",
        "LDI2L",
        "LDI2H",
        "LDI2RH",
        "LDI2TH",
        "LDCW",
        "LDCL",
        "LDCH",
        "LDCRH",
        "LDCTH",
        "",
        "",
    ],
    "15LD3": [
        "",
        "LD3WG",
        "LD3WS",
        "LD3AW",
        "LD3AWN",
        "LD3PW",
        "LD3PWN",
        "LD3L",
        "LD3ICA",
        "LD3ICP",
        "LD3ICB",
        "LD3ICL",
        "LD3NH",
        "LD3H",
        "LD3AL",
        "LD3PL",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "16LD4": [
        "",
        "LD4WG",
        "LD4WS",
        "LD4AW",
        "LD4AWN",
        "LD4PW",
        "LD4PWN",
        "LD4L",
        "LD4ICA",
        "LD4ICP",
        "LD4ICB",
        "LD4ICL",
        "LD4NH",
        "LD4H",
        "LD4AL",
        "LD4PL",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "17UMX": [
        "UMXTOOTH",
        "UMXWG",
        "UMXWS",
        "",
        "",
        "UMXAW",
        "UMXAWN",
        "UMXPW",
        "UMXPWN",
        "UMXL",
        "UMXICA",
        "UMXICP",
        "UMXICB",
        "UMXICL",
        "UMXNH",
        "UMXH",
        "UMXAL",
        "UMXPL",
        "",
        "",
        "",
        "",
    ],
    # Common variable name typo, so, add a line to deal with it:
    "18UPX": [
        "",
        "UPX3WG",
        "UPX4WG",
        "UPX3WS",
        "UPX4WS",
        "UPX3W",
        "UPX3L",
        "UPX3IC",
        "UPX3H",
        "UPX3FH",
        "UPX3AL",
        "UPX3PL",
        "UPX4W",
        "UPX4L",
        "UPX4IC",
        "UPX4H",
        "UPX4FH",
        "UPX4AL",
        "UPX4PL",
        "",
        "",
        "",
    ],
    "19UPX": [
        "",
        "UPX3WG",
        "UPX4WG",
        "UPX3WS",
        "UPX4WS",
        "UPX3W",
        "UPX3L",
        "UPX3IC",
        "UPX3H",
        "UPX3FH",
        "UPX3AL",
        "UPX3PL",
        "UPX4W",
        "UPX4L",
        "UPX4IC",
        "UPX4H",
        "UPX4FH",
        "UPX4AL",
        "UPX4PL",
        "",
        "",
        "",
    ],
    "20LMX": [
        "LMXTOOTH",
        "LMXWG",
        "LMXWS",
        "LMXAW",
        "LMXAWN",
        "LMXPW",
        "LMXPWN",
        "LMXL",
        "LMXICA",
        "LMXICP",
        "LMXICB",
        "LMXICL",
        "LMXNH",
        "LMXH",
        "LMXAL",
        "LMXPL",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
}

"""
List of headers in teeth.csv file. Have to rewrite this because header/field
names are missing for all measurements, which makes using a dictreader difficult.
This does still increase fragility of code, as it means column ordering can't change.
m1–m21 are the measurements and their numbers are the index numbers that are used
for lookups in variable_names.
"""
field_names = [
    "uid",
    "tooth",
    "hypocode",
    "observer",
    "sexno",
    "group_id",
    "xtooth",
    "m1",
    "m2",
    "m3",
    "m4",
    "m5",
    "m6",
    "m7",
    "m8",
    "m9",
    "m10",
    "m11",
    "m12",
    "m13",
    "m14",
    "m15",
    "m16",
    "m17",
    "m18",
    "m19",
    "m20",
    "m21",
    "comments",
    "cast",
]

"""
Lookup table of variable ids, given the variable name.

This section is hand-edited and delicate—be careful changing it!
"""
variable_ids = {
    "UI1W": 225,
    "UI1LA": 226,
    "UI1L": 227,
    "UI1H": 228,
    "UI1RH": 229,
    "UI1TH": 230,
    "UI2W": 231,
    "UI2LA": 232,
    "UI2L": 233,
    "UI2H": 234,
    "UI2RH": 235,
    "UI2TH": 236,
    "UCW": 237,
    "UCL": 238,
    "UCH": 239,
    "UCRH": 240,
    "UCTH": 241,
    "UP3WG": 242,
    "UP3WS": 243,
    "UP3W": 244,
    "UP3L": 245,
    "UP3IC": 246,
    "UP3H": 247,
    "UP3FH": 248,
    "UP3AL": 249,
    "UP3PL": 250,
    "UP4WG": 251,
    "UP4WS": 252,
    "UP4W": 253,
    "UP4L": 254,
    "UP4IC": 255,
    "UP4H": 256,
    "UP4FH": 257,
    "UP4AL": 258,
    "UP4PL": 259,
    "UM1WG": 260,
    "UM1WS": 261,
    "UM1AW": 262,
    "UM1AWN": 263,
    "UM1PW": 264,
    "UM1PWN": 265,
    "UM1L": 266,
    "UM1ICA": 267,
    "UM1ICP": 268,
    "UM1ICB": 269,
    "UM1ICL": 270,
    "UM1NH": 271,
    "UM1H": 272,
    "UM1AL": 273,
    "UM1PL": 274,
    "UM2WG": 275,
    "UM2WS": 276,
    "UM2AW": 277,
    "UM2AWN": 278,
    "UM2PW": 279,
    "UM2PWN": 280,
    "UM2L": 281,
    "UM2ICA": 282,
    "UM2ICP": 283,
    "UM2ICB": 284,
    "UM2ICL": 285,
    "UM2NH": 286,
    "UM2H": 287,
    "UM2AL": 288,
    "UM2PL": 289,
    "UM3WG": 290,
    "UM3WS": 291,
    "UM3AW": 292,
    "UM3AWN": 293,
    "UM3PW": 294,
    "UM3PWN": 295,
    "UM3L": 296,
    "UM3ICA": 297,
    "UM3ICP": 298,
    "UM3ICB": 299,
    "UM3ICL": 300,
    "UM3NH": 301,
    "UM3H": 302,
    "UM3AL": 303,
    "UM3PL": 304,
    "UDI1W": 305,
    "UDI1LA": 306,
    "UDI1L": 307,
    "UDI1H": 308,
    "UDI1RH": 309,
    "UDI1TH": 310,
    "UDI2W": 311,
    "UDI2LA": 312,
    "UDI2L": 313,
    "UDI2H": 314,
    "UDI2RH": 315,
    "UDI2TH": 316,
    "UDCW": 317,
    "UDCL": 318,
    "UDCH": 319,
    "UDCRH": 320,
    "UDCTH": 321,
    "UD3WG": 322,
    "UD3WS": 323,
    "UD3AW": 324,
    "UD3AWN": 325,
    "UD3PW": 326,
    "UD3PWN": 327,
    "UD3L": 328,
    "UD3ICA": 329,
    "UD3ICP": 330,
    "UD3ICB": 331,
    "UD3ICL": 332,
    "UD3NH": 333,
    "UD3H": 334,
    "UD3AL": 335,
    "UD3PL": 336,
    "UD4WG": 337,
    "UD4WS": 338,
    "UD4AW": 339,
    "UD4AWN": 340,
    "UD4PW": 341,
    "UD4PWN": 342,
    "UD4L": 343,
    "UD4ICA": 344,
    "UD4ICP": 345,
    "UD4ICB": 346,
    "UD4ICL": 347,
    "UD4NH": 348,
    "UD4H": 349,
    "UD4AL": 350,
    "UD4PL": 351,
    "UPX3WG": 352,
    "UPX3WS": 353,
    "UPX3W": 354,
    "UPX3L": 355,
    "UPX3IC": 356,
    "UPX3H": 357,
    "UPX3FH": 358,
    "UPX3AL": 359,
    "UPX3PL": 360,
    "UPX4WG": 361,
    "UPX4WS": 362,
    "UPX4W": 363,
    "UPX4L": 364,
    "UPX4IC": 365,
    "UPX4H": 366,
    "UPX4FH": 367,
    "UPX4AL": 368,
    "UPX4PL": 369,
    "UMXTOOTH": 370,  # Following are probably upper molar.
    "UMXWG": 371,
    "UMXWS": 372,
    "UMXAW": 373,
    "UMXAWN": 374,
    "UMXPW": 375,
    "UMXPWN": 376,
    "UMXL": 377,
    "UMXICA": 378,
    "UMXICP": 379,
    "UMXICB": 380,
    "UMXICL": 381,
    "UMXNH": 382,
    "UMXH": 383,
    "UMXAL": 384,
    "UMXPL": 385,
    "LI1W": 386,
    "LI1LA": 387,
    "LI1L": 388,
    "LI1H": 389,
    "LI1RH": 390,
    "LI1TH": 391,
    "LI2W": 392,
    "LI2LA": 393,
    "LI2L": 394,
    "LI2H": 395,
    "LI2RH": 396,
    "LI2TH": 397,
    "LCW": 398,
    "LCL": 399,
    "LCH": 400,
    "LCRH": 401,
    "LCTH": 402,
    "LP3W": 403,
    "LP3LA": 404,
    "LP3L": 405,
    "LP3FL": 406,
    "LP3H": 407,
    "LP3PL": 408,
    "LP3HX": 409,
    "LP4WG": 410,
    "LP4WS": 411,
    "LP4W": 412,
    "LP4L": 413,
    "LP4IC": 414,
    "LP4NH": 415,
    "LP4MH": 416,
    "LP4FH": 417,
    "LP4ALN": 418,
    "LP4PLN": 419,
    "LP4ALM": 420,  # was LP4AL
    "LP4PLM": 421,  # was LP$PL
    "LM1WG": 422,
    "LM1WS": 423,
    "LM1AW": 424,
    "LM1AWN": 425,
    "LM1PW": 426,
    "LM1PWN": 427,
    "LM1L": 428,
    "LM1ICA": 429,
    "LM1ICP": 430,
    "LM1ICB": 431,
    "LM1ICL": 432,
    "LM1NH": 433,
    "LM1H": 434,
    "LM1AL": 435,
    "LM1PL": 436,
    "LM2WG": 437,
    "LM2WS": 438,
    "LM2AW": 439,
    "LM2AWN": 440,
    "LM2PW": 441,
    "LM2PWN": 442,
    "LM2L": 443,
    "LM2ICA": 444,
    "LM2ICP": 445,
    "LM2ICB": 446,
    "LM2ICL": 447,
    "LM2NH": 448,
    "LM2H": 449,
    "LM2AL": 450,
    "LM2PL": 451,
    "LM3WG": 452,
    "LM3WS": 453,
    "LM3AW": 454,
    "LM3AWN": 455,
    "LM3PW": 456,
    "LM3PWN": 457,
    "LM3L": 458,
    "LM3ICA": 459,
    "LM3ICP": 460,
    "LM3ICB": 461,
    "LM3ICL": 462,
    "LM3NH": 463,
    "LM3H": 464,
    "LM3AL": 465,
    "LM3PL": 466,
    "LM3HW": 467,
    "LM3HW2": 468,
    "LM3IHB": 469,
    "LM3IHL": 470,
    "LM3AL2": 471,
    "LM3HYL": 472,
    "LDI1W": 473,
    "LDI1LA": 474,
    "LDI1L": 475,
    "LDI1H": 476,
    "LDI1RH": 477,
    "LDI1TH": 478,
    "LDI2W": 479,
    "LDI2LA": 480,
    "LDI2L": 481,
    "LDI2H": 482,
    "LDI2RH": 483,
    "LDI2TH": 484,
    "LDCW": 485,
    "LDCL": 486,
    "LDCH": 487,
    "LDCRH": 488,
    "LDCTH": 489,
    "LD3WG": 490,
    "LD3WS": 491,
    "LD3AW": 492,
    "LD3AWN": 493,
    "LD3PW": 494,
    "LD3PWN": 495,
    "LD3L": 496,
    "LD3ICA": 497,
    "LD3ICP": 498,
    "LD3ICB": 499,
    "LD3ICL": 500,
    "LD3NH": 501,
    "LD3H": 502,
    "LD3AL": 503,
    "LD3PL": 504,
    "LD4WG": 505,
    "LD4WS": 506,
    "LD4AW": 507,
    "LD4AWN": 508,
    "LD4PW": 509,
    "LD4PWN": 510,
    "LD4L": 511,
    "LD4ICA": 512,
    "LD4ICP": 513,
    "LD4ICB": 514,
    "LD4ICL": 515,
    "LD4NH": 516,
    "LD4H": 517,
    "LD4AL": 518,
    "LD4PL": 519,
    "LMXTOOTH": 520,  # Following are probably lower molar.
    "LMXWG": 521,
    "LMXWS": 522,
    "LMXAW": 523,
    "LMXAWN": 524,
    "LMXPW": 525,
    "LMXPWN": 526,
    "LMXL": 527,
    "LMXICA": 528,
    "LMXICP": 529,
    "LMXICB": 530,
    "LMXICL": 531,
    "LMXNH": 532,
    "LMXH": 533,
    "LMXAL": 534,
    "LMXPL": 535,
    "UPXTOOTH": 536,  # Probably upper premolar.
}

# Teeth that are likely upper molars.
UMXTOOTH = {
    "1": "probably upper M1",
    "2": "probably upper M2",
    "3": "probably upper M3",
    "4": "possibly upper M1",
    "5": "possibly upper M2",
    "6": "possibly upper M3",
    "7": "possibly upper M1 or upper M2",
    "8": "possibly upper M2 or upper M3",
    "9": "upper molar position uncertain",
}

# Teeth that are probably lower molars.
LMXTOOTH = {
    "1": "probably lower M1",
    "2": "probably lower M2",
    "3": "probably lower M3",
    "4": "possibly lower M1",
    "5": "possibly lower M2",
    "6": "possibly lower M3",
    "7": "possibly lower M1 or lower M2",
    "8": "possibly lower M2 or lower M3",
    "9": "lower molar position uncertain",
}

# Teeth that are likely upper premolars.
UPXTOOTH = {
    "3": "probably an upper third premolar",
    "4": "probably an upper fourth premolar",
    "6": "possibly an upper third premolar",
    "8": "possibly an upper fourth premolar",
    "9": "upper premolar position uncertain",
}
